// generated by titan, dont modify anything otherwise it might break =)
module simple_neuron (
	input wire clock,
	input logic [31:0] x0,
	input logic [31:0] x1,
	input logic [31:0] x2,
	input logic [31:0] x3,
	// input logic [31:0] w0,
	// input logic [31:0] w1,
	// input logic [31:0] w2,
	// input logic [31:0] w3,
	output wire [31:0] r
);
	logic [31:0] titan_id_0;
	logic [31:0] titan_id_1;
	logic [31:0] titan_id_3;
	logic [31:0] titan_id_4;
	logic [31:0] titan_id_2;
	logic [31:0] titan_id_5;
	logic [31:0] titan_id_6;
	logic [31:0] titan_id_8;
	always_ff @ (posedge clock) begin
		titan_id_0 <= 3 * x0;
		titan_id_1 <= 4 * x1;
		titan_id_3 <= -1 * x2;
		titan_id_4 <= -2 * x3;
		titan_id_2 <= titan_id_0 + titan_id_1;
		titan_id_5 <= titan_id_3 + titan_id_4;
		titan_id_6 <= titan_id_2 + titan_id_5;
		titan_id_8 <= titan_id_6 > 0 ? titan_id_6 : 0;
	end
	assign r = titan_id_8;
endmodule
